language: objective-c
xcode_project: SwiftyLog.xcodeproj
xcode_scheme: SwiftyLog

osx_image: xcode9.2
xcode_sdk: iphonesimulator9.2

script: xcodebuild clean && xcodebuild build -project SwiftyLog.xcodeproj -scheme SwiftyLog